# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-03-11 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bike_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('status', models.BooleanField(default=True)),
                ('last_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recoder',
            fields=[
                ('recoder_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('lock_time', models.DateTimeField(auto_now_add=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikemanage.Bike')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=32)),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('telephone', models.CharField(max_length=16)),
                ('qq_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='recoder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikemanage.User'),
        ),
        migrations.AddField(
            model_name='bike',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikemanage.User'),
        ),
    ]
