# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikemanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
