# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikemanage', '0002_auto_20190325_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoder',
            name='user',
        ),
    ]
