# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikemanage', '0003_remove_recoder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoder',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bike',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
