# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikemanage', '0004_auto_20190331_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoder',
            name='recoder_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
